package repositories

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	Revoked   bool
	CreatedAt time.Time
}

type RefreshTokenRepository struct {
	db *pgxpool.Pool
}

func NewRefreshTokenRepository(db *pgxpool.Pool) *RefreshTokenRepository {
	return &RefreshTokenRepository{db: db}
}

// Create stores a new refresh token.
// The token itself is never stored — only its SHA-256 hash.
// The raw token is generated by the auth service and returned to the client.
func (r *RefreshTokenRepository) Create(ctx context.Context, userID, tokenHash string, expiresAt time.Time) error {
	query := `
		INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
		VALUES ($1, $2, $3)
	`

	_, err := r.db.Exec(ctx, query, userID, tokenHash, expiresAt)
	return err
}

// FindByHash looks up a refresh token by its SHA-256 hash.
// This is how we validate an incoming refresh request —
// we hash the token the client sent and look for a match.
// Returns ErrNotFound if no token matches.
func (r *RefreshTokenRepository) FindByHash(ctx context.Context, tokenHash string) (*RefreshToken, error) {
	query := `
		SELECT id, user_id, token_hash, expires_at, revoked, created_at
		FROM refresh_tokens
		WHERE token_hash = $1
	`

	token := &RefreshToken{}
	err := r.db.QueryRow(ctx, query, tokenHash).Scan(
		&token.ID,
		&token.UserID,
		&token.TokenHash,
		&token.ExpiresAt,
		&token.Revoked,
		&token.CreatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	return token, nil
}

// Revoke marks a single refresh token as revoked by its ID.
// Called immediately when a token is used — rotation means
// a used token can never be used again.
func (r *RefreshTokenRepository) Revoke(ctx context.Context, id string) error {
	query := `
		UPDATE refresh_tokens
		SET revoked = TRUE
		WHERE id = $1
	`

	_, err := r.db.Exec(ctx, query, id)
	return err
}

// RevokeAllForUser marks every refresh token for a user as revoked.
// Called in two situations:
// 1. User logs in — kill all existing sessions
// 2. Token theft detected — kill everything immediately
func (r *RefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID string) error {
	query := `
		UPDATE refresh_tokens
		SET revoked = TRUE
		WHERE user_id = $1
		AND revoked = FALSE
	`

	_, err := r.db.Exec(ctx, query, userID)
	return err
}

// DeleteExpired removes tokens that are past their expiry date.
// In V1 this is called manually. V2 will run it on a schedule.
func (r *RefreshTokenRepository) DeleteExpired(ctx context.Context) error {
	query := `
		DELETE FROM refresh_tokens
		WHERE expires_at < NOW()
	`

	_, err := r.db.Exec(ctx, query)
	return err
}